name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: # <--- Adicione esta seção
      contents: write # <--- Esta permissão é crucial para criar releases

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token gerado automaticamente pelo GitHub
      with:
        tag_name: v${{ github.run_number }} # Exemplo de tag: v1, v2, etc. Você pode ajustar.
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # URL para upload do asset
        asset_path: target/release/rmsql
        asset_name: rmsql
        asset_content_type: application/x-pie-executable
